# Generated by Django 3.0.7 on 2020-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200714_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
