# Generated by Django 3.0.7 on 2020-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200714_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_time_of_subscription',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
