# Generated by Django 3.0.7 on 2020-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200714_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_time_of_subscription',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
