# Generated by Django 3.0.7 on 2020-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200714_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/body_images'),
        ),
    ]
