# Generated by Django 3.0.7 on 2020-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200714_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
