# Generated by Django 3.0.7 on 2020-07-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_plans_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='slug',
        ),
    ]
