# Generated by Django 3.0.7 on 2020-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_plans_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
