# Generated by Django 3.0.7 on 2020-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200715_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='validity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
