# Generated by Django 3.0.7 on 2020-07-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_plans_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='validity',
        ),
    ]
