# Generated by Django 3.0.7 on 2020-07-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_plans_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Batches'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Plans'),
        ),
    ]
