# Generated by Django 3.0.7 on 2020-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_plans_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousStarterPlanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.CharField(blank=True, max_length=200, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
