# Generated by Django 3.0.7 on 2020-07-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_previousstarterplanuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousstarterplanuser',
            name='plan',
        ),
    ]
