# Generated by Django 3.0.7 on 2020-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_profile_date_last_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregisteredprofiles',
            options={'verbose_name': 'User Request', 'verbose_name_plural': 'User Requests'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
