# Generated by Django 3.1.2 on 2021-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200918_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='is_default',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
