# Generated by Django 3.1.2 on 2021-01-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_plans_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
