# Generated by Django 3.1.2 on 2021-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20210105_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='is_default',
        ),
        migrations.AddField(
            model_name='plans',
            name='plan_Type',
            field=models.CharField(choices=[('D', 'Default'), ('N', 'Normal')], default='N', max_length=10),
        ),
    ]
