# Generated by Django 3.1.2 on 2021-01-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20210105_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='plan_Type',
            new_name='plan_type',
        ),
    ]
