# Generated by Django 3.0.3 on 2020-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='achievements')),
                ('year', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=1000)),
                ('institution', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='events')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=500)),
            ],
        ),
    ]
