# Generated by Django 3.0.3 on 2020-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='events')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='anniversary'),
        ),
    ]
