# Generated by Django 3.0.3 on 2020-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0002_auto_20200527_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anniversary',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notices',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
