# Generated by Django 3.0.3 on 2020-05-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0004_auto_20200527_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnival_name', models.CharField(max_length=300)),
                ('carnival_img', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/carnivals')),
                ('carnival_desc', models.CharField(max_length=3000)),
                ('carnival_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=300)),
                ('social_img', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/socials')),
                ('social_desc', models.CharField(max_length=3000)),
                ('social_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=300)),
                ('b_img', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/testimonials')),
                ('a_img', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/testimonials')),
                ('b_weight', models.IntegerField()),
                ('a_weight', models.IntegerField()),
                ('duration', models.CharField(max_length=200)),
                ('total_loass', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/achievements'),
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/anniversary'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/events'),
        ),
    ]
