# Generated by Django 3.0.3 on 2020-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0005_auto_20200528_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnivals',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='socials',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
