# Generated by Django 3.0.3 on 2020-05-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0006_auto_20200528_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='total_loass',
            new_name='total_loss',
        ),
    ]
