# Generated by Django 3.0.3 on 2020-05-31 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0007_auto_20200528_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='image',
        ),
        migrations.RemoveField(
            model_name='anniversary',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carnivals',
            name='carnival_img',
        ),
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='social_img',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('achievements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Achievements')),
                ('anniversary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Anniversary')),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Events')),
                ('socials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Socials')),
            ],
        ),
    ]
