# Generated by Django 3.0.3 on 2020-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0008_auto_20200531_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='review',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
