# Generated by Django 3.0.3 on 2020-06-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0009_testimonials_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socials',
            old_name='social_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='socials',
            old_name='social_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='socials',
            old_name='social_name',
            new_name='name',
        ),
    ]
