# Generated by Django 3.0.7 on 2020-06-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0010_auto_20200608_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('anniversary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Anniversary')),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Events')),
            ],
        ),
        migrations.CreateModel(
            name='SocialImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('socials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_view.Socials')),
            ],
        ),
        migrations.AddField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/achievements'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
