# Generated by Django 2.1 on 2020-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0014_auto_20200612_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/achievements'),
        ),
        migrations.AlterField(
            model_name='anniversaryimages',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc'),
        ),
        migrations.AlterField(
            model_name='socialimages',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/misc'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='a_img',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/testimonials', verbose_name='After Image'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='b_img',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/testimonials', verbose_name='Before Image'),
        ),
    ]
