# Generated by Django 3.0.7 on 2020-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0017_auto_20200713_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/exercises', verbose_name='Image')),
                ('video_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Video Link')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
    ]
