# Generated by Django 3.0.7 on 2020-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0018_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='a_weight',
            field=models.FloatField(verbose_name='After Weight'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='b_weight',
            field=models.FloatField(verbose_name='Before Weight'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='total_loss',
            field=models.FloatField(verbose_name='Total Loss (in Kgs)'),
        ),
    ]
